import { PropertyListing } from './types';

export const mockListings: PropertyListing[] = [
  {
    id: '1',
    title: 'Modern Villa in East Legon',
    price: 'GHS 450,000',
    location: 'East Legon, Accra',
    bedrooms: 4,
    bathrooms: 3,
    area: '2,500 sq ft',
    image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=300',
    views: 45,
    interested: 8,
    status: 'active',
    description: 'Stunning modern villa with contemporary design and luxury amenities',
    type: 'residential',
    agent: {
      id: '1',
      name: 'Sarah Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face',
      phone: '+233 24 123 4567',
      email: 'sarah.johnson@realestate.com',
      rating: 4.8
    },
    createdAt: '2024-01-15',
    updatedAt: '2024-01-20',
    featured: true,
    priority: 'high',
    tags: ['luxury', 'modern', 'villa'],
    amenities: ['Swimming Pool', 'Garden', 'Security', 'Parking']
  },
  {
    id: '2',
    title: 'Commercial Complex',
    price: 'GHS 1,200,000',
    location: 'Spintex Road, Accra',
    bedrooms: undefined,
    bathrooms: 6,
    area: '8,000 sq ft',
    image: 'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=300',
    views: 32,
    interested: 5,
    status: 'active',
    description: 'Prime commercial complex in high-traffic area with excellent ROI potential',
    type: 'commercial',
    agent: {
      id: '2',
      name: 'Michael Chen',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
      phone: '+233 20 987 6543',
      email: 'michael.chen@realestate.com',
      rating: 4.9
    },
    createdAt: '2024-01-10',
    updatedAt: '2024-01-18',
    featured: false,
    priority: 'medium',
    tags: ['commercial', 'investment', 'high-traffic'],
    amenities: ['24/7 Security', 'Parking', 'Elevator', 'Air Conditioning']
  },
  {
    id: '3',
    title: 'Family Home in Kumasi',
    price: 'GHS 280,000',
    location: 'Asokore Mampong, Kumasi',
    bedrooms: 3,
    bathrooms: 2,
    area: '1,800 sq ft',
    image: 'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=300',
    views: 28,
    interested: 12,
    status: 'pending',
    description: 'Cozy family home in quiet neighborhood with good schools nearby',
    type: 'residential',
    agent: {
      id: '3',
      name: 'Emma Wilson',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
      phone: '+233 26 456 7890',
      email: 'emma.wilson@realestate.com',
      rating: 4.7
    },
    createdAt: '2024-01-05',
    updatedAt: '2024-01-15',
    featured: false,
    priority: 'low',
    tags: ['family', 'quiet', 'schools'],
    amenities: ['Garden', 'Security', 'Parking']
  },
  {
    id: '4',
    title: 'Luxury Apartment',
    price: 'GHS 650,000',
    location: 'Cantonments, Accra',
    bedrooms: 3,
    bathrooms: 2,
    area: '2,200 sq ft',
    image: 'https://images.pexels.com/photos/154532/pexels-photo-154532.jpeg?auto=compress&cs=tinysrgb&w=300',
    views: 67,
    interested: 15,
    status: 'active',
    description: 'Premium apartment with city views and luxury amenities',
    type: 'residential',
    agent: {
      id: '4',
      name: 'David Brown',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
      phone: '+233 27 789 0123',
      email: 'david.brown@realestate.com',
      rating: 4.6
    },
    createdAt: '2024-01-12',
    updatedAt: '2024-01-22',
    featured: true,
    priority: 'urgent',
    tags: ['luxury', 'apartment', 'city-view'],
    amenities: ['Gym', 'Swimming Pool', 'Security', 'Parking', 'Concierge']
  },
  {
    id: '5',
    title: 'Industrial Warehouse',
    price: 'GHS 850,000',
    location: 'Tema Industrial Area',
    bedrooms: undefined,
    bathrooms: 4,
    area: '15,000 sq ft',
    image: 'https://images.pexels.com/photos/158240/pexels-photo-158240.jpeg?auto=compress&cs=tinysrgb&w=300',
    views: 23,
    interested: 3,
    status: 'active',
    description: 'Large industrial warehouse with loading docks and office space',
    type: 'industrial',
    agent: {
      id: '5',
      name: 'Lisa Anderson',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop&crop=face',
      phone: '+233 24 567 8901',
      email: 'lisa.anderson@realestate.com',
      rating: 4.9
    },
    createdAt: '2024-01-08',
    updatedAt: '2024-01-16',
    featured: false,
    priority: 'medium',
    tags: ['industrial', 'warehouse', 'loading-docks'],
    amenities: ['Loading Docks', 'Office Space', 'Security', 'Parking']
  },
  {
    id: '6',
    title: 'Mixed-Use Development',
    price: 'GHS 2,500,000',
    location: 'Osu, Accra',
    bedrooms: 8,
    bathrooms: 6,
    area: '12,000 sq ft',
    image: 'https://images.pexels.com/photos/148640/pexels-photo-148640.jpeg?auto=compress&cs=tinysrgb&w=300',
    views: 89,
    interested: 22,
    status: 'sold',
    description: 'Premium mixed-use development with retail and residential units',
    type: 'mixed-use',
    agent: {
      id: '6',
      name: 'Chris Lee',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
      phone: '+233 25 234 5678',
      email: 'chris.lee@realestate.com',
      rating: 4.8
    },
    createdAt: '2023-12-20',
    updatedAt: '2024-01-25',
    featured: true,
    priority: 'high',
    tags: ['mixed-use', 'premium', 'retail'],
    amenities: ['Retail Space', 'Residential Units', 'Parking', 'Security']
  }
];

export const sampleFilters = {
  status: 'active' as const,
  type: 'residential' as const,
  priceRange: { min: 100000, max: 1000000 },
  location: 'Accra',
  bedrooms: 3,
  bathrooms: 2
}; 